if SERVER then
    resource.AddFile("sound/anchovies/anchovies_standard_en.ogg")
    resource.AddFile("sound/anchovies/anchovies_standard_de.ogg")
    resource.AddFile("sound/anchovies/anchovies_shark.ogg")
    resource.AddFile("sound/anchovies/this_is_patrick_1.ogg")
    resource.AddFile("sound/anchovies/this_is_patrick_2.ogg")
    resource.AddFile("sound/anchovies/this_is_patrick_3.ogg")

    resource.AddFile("models/spongebob_anchovies/spongebob_anchovies_bus_model/bus.dx80.vtx")
    resource.AddFile("models/spongebob_anchovies/spongebob_anchovies_bus_model/bus.dx90.vtx")
    resource.AddFile("models/spongebob_anchovies/spongebob_anchovies_bus_model/bus.mdl")
    resource.AddFile("models/spongebob_anchovies/spongebob_anchovies_bus_model/bus.phy")
    resource.AddFile("models/spongebob_anchovies/spongebob_anchovies_bus_model/bus.sw.vtx")
    resource.AddFile("models/spongebob_anchovies/spongebob_anchovies_bus_model/bus.vvd")

    resource.AddFile("models/spongebob_anchovies/spongebob_anchovie_phone_model/phone.dx80.vtx")
    resource.AddFile("models/spongebob_anchovies/spongebob_anchovie_phone_model/phone.dx90.vtx")
    resource.AddFile("models/spongebob_anchovies/spongebob_anchovie_phone_model/phone.mdl")
    resource.AddFile("models/spongebob_anchovies/spongebob_anchovie_phone_model/phone.phy")
    resource.AddFile("models/spongebob_anchovies/spongebob_anchovie_phone_model/phone.sw.vtx")
    resource.AddFile("models/spongebob_anchovies/spongebob_anchovie_phone_model/phone.vvd")

    resource.AddFile("models/spongebob_anchovies/c_spongebob_anchovie_phone_model/c_phone.dx80.vtx")
    resource.AddFile("models/spongebob_anchovies/c_spongebob_anchovie_phone_model/c_phone.dx90.vtx")
    resource.AddFile("models/spongebob_anchovies/c_spongebob_anchovie_phone_model/c_phone.mdl")
    resource.AddFile("models/spongebob_anchovies/c_spongebob_anchovie_phone_model/c_phone.phy")
    resource.AddFile("models/spongebob_anchovies/c_spongebob_anchovie_phone_model/c_phone.sw.vtx")
    resource.AddFile("models/spongebob_anchovies/c_spongebob_anchovie_phone_model/c_phone.vvd")

    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_bus_mats/car.vmt")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_bus_mats/felge.vmt")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_bus_mats/glass.vmt")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_bus_mats/lcdbackground.vmt")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_bus_mats/lightback.vmt")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_bus_mats/lightfront.vmt")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_bus_mats/metal.vmt")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_bus_mats/screw.vmt")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_bus_mats/text.vmt")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_bus_mats/wheel.vmt")

    resource.AddFile("materials/VGUI/ttt/weapon_anchovie_gun.png")

    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_anchovie_mats/anchovie_1.png")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_anchovie_mats/anchovie_2.png")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_anchovie_mats/anchovie_3.png")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_anchovie_mats/anchovie_4.png")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_anchovie_mats/anchovie_5.png")
    resource.AddFile("materials/spongebob_anchovies/spongebob_anchovies_anchovie_mats/anchovie_6.png")
end